name: educationalapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/KidsEuro.jpeg
    - assets/images/kidsTrends.jpeg
    - assets/images/female.png
    - assets/images/male.png
    - assets/images/mm.jpeg   # âœ… corrected extension
    - assets/images/arrow.jpeg
    - assets/images/iconback.jpg
    - assets/images/backicon.jpg
    - assets/images/teachericon.png
    - assets/images/icon1.png
    - assets/images/icon2.png
    - assets/images/icon3.png
fonts:
  - family: circe
    fonts:
      - asset: assets/fonts/Circe-Regular.ttf
      - asset: assets/fonts/Circe-Bold.ttf
        weight: 600